services:
  backend:
    volumes:
      - ./backend:/app

  scheduler:
    volumes:
      - ./backend:/app

  backend-tests:
    volumes:
      - ./backend:/app
      - ./backend/tests:/app/tests
      - ./backend/pytest.ini:/app/pytest.ini:ro
